package com.parking.entity;

import jakarta.persistence.*;

/*
==============================================================================
FILE: ParkingFloor.java

PURPOSE:
--------
This entity represents a parking floor in the
Smart Vehicle Parking Management System.

Example:

Floor 1 → 50 parking slots
Floor 2 → 40 parking slots
Floor 3 → 30 parking slots

This class is connected to the "parking_floors" table
in the MySQL database.

==============================================================================
*/

@Entity
@Table(name = "parking_floors")
public class ParkingFloor {

    /*
    ==========================================================================
    FIELD: id

    PURPOSE:
    --------
    Unique ID of the parking floor.

    The ID is automatically generated by MySQL.
    ==========================================================================
    */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    /*
    ==========================================================================
    FIELD: floorNumber

    PURPOSE:
    --------
    Stores the floor number.

    Examples:

    1
    2
    3

    This field represents the physical parking floor.
    ==========================================================================
    */

    @Column(nullable = false, unique = true)
    private Integer floorNumber;


    /*
    ==========================================================================
    FIELD: totalSlots

    PURPOSE:
    --------
    Stores the total number of parking slots available
    on this floor.

    Example:

    Floor 1 → 50 slots
    ==========================================================================
    */

    @Column(nullable = false)
    private Integer totalSlots;


    /*
    ==========================================================================
    DEFAULT CONSTRUCTOR

    Required by JPA/Hibernate.
    ==========================================================================
    */

    public ParkingFloor() {
    }


    /*
    ==========================================================================
    PARAMETERIZED CONSTRUCTOR
    ==========================================================================
    */

    public ParkingFloor(
            Long id,
            Integer floorNumber,
            Integer totalSlots) {

        this.id = id;
        this.floorNumber = floorNumber;
        this.totalSlots = totalSlots;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR ID
    ==========================================================================
    */

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR FLOOR NUMBER
    ==========================================================================
    */

    public Integer getFloorNumber() {
        return floorNumber;
    }

    public void setFloorNumber(Integer floorNumber) {
        this.floorNumber = floorNumber;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR TOTAL SLOTS
    ==========================================================================
    */

    public Integer getTotalSlots() {
        return totalSlots;
    }

    public void setTotalSlots(Integer totalSlots) {
        this.totalSlots = totalSlots;
    }
}