package com.parking.entity;

import jakarta.persistence.*;

/*
==============================================================================
FILE: ParkingSlot.java

PURPOSE:
--------
This entity represents an individual parking slot.

Each parking slot belongs to a particular parking floor.

Example:

Floor 1
    ↓
    A1 → AVAILABLE
    A2 → OCCUPIED
    A3 → AVAILABLE

The entity is mapped to the "parking_slots" table in MySQL.

==============================================================================
*/

@Entity
@Table(name = "parking_slots")
public class ParkingSlot {

    /*
    ==========================================================================
    FIELD: id

    PURPOSE:
    --------
    Unique ID of the parking slot.

    Automatically generated by MySQL.
    ==========================================================================
    */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    /*
    ==========================================================================
    FIELD: slotNumber

    PURPOSE:
    --------
    Identifies the individual parking slot.

    Examples:

    A1
    A2
    A3
    B1
    B2
    ==========================================================================
    */

    @Column(nullable = false)
    private String slotNumber;


    /*
    ==========================================================================
    FIELD: status

    PURPOSE:
    --------
    Stores the current status of the parking slot.

    Possible values:

    AVAILABLE
    OCCUPIED
    RESERVED
    ==========================================================================
    */

    @Column(nullable = false)
    private String status;


    /*
    ==========================================================================
    FIELD: floor

    PURPOSE:
    --------
    Connects this parking slot to a parking floor.

    Example:

    Slot A1 → Floor 1
    Slot A2 → Floor 1
    Slot B1 → Floor 2

    Many parking slots can belong to one parking floor.

    ==========================================================================
    */

    @ManyToOne
    @JoinColumn(name = "floor_id", nullable = false)
    private ParkingFloor floor;


    /*
    ==========================================================================
    DEFAULT CONSTRUCTOR

    Required by JPA/Hibernate.
    ==========================================================================
    */

    public ParkingSlot() {
    }


    /*
    ==========================================================================
    PARAMETERIZED CONSTRUCTOR
    ==========================================================================
    */

    public ParkingSlot(
            Long id,
            String slotNumber,
            String status,
            ParkingFloor floor) {

        this.id = id;
        this.slotNumber = slotNumber;
        this.status = status;
        this.floor = floor;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR ID
    ==========================================================================
    */

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR SLOT NUMBER
    ==========================================================================
    */

    public String getSlotNumber() {
        return slotNumber;
    }

    public void setSlotNumber(String slotNumber) {
        this.slotNumber = slotNumber;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR STATUS
    ==========================================================================
    */

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR FLOOR
    ==========================================================================
    */

    public ParkingFloor getFloor() {
        return floor;
    }

    public void setFloor(ParkingFloor floor) {
        this.floor = floor;
    }
}