package com.parking.entity;

import com.parking.enums.Role;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

/*
==============================================================================
FILE: User.java

PURPOSE:
--------
This entity represents a user of the Smart Vehicle Parking Management System.

A user can have one of two roles:

1. ADMIN
2. CUSTOMER

This class is mapped to the "users" table in MySQL.

==============================================================================
*/

@Entity
@Table(name = "users")
public class User {

    /*
    ==========================================================================
    FIELD: id

    PURPOSE:
    --------
    Unique ID of the user.

    The ID is automatically generated by the database.
    ==========================================================================
    */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    /*
    ==========================================================================
    FIELD: name

    PURPOSE:
    --------
    Stores the user's full name.

    IMPORTANT:
    ----------
    Java field name = name
    MySQL column name = full_name

    @Column(name = "full_name") connects the Java field
    with the existing MySQL column.
    ==========================================================================
    */

    @NotBlank(message = "Name is required")
    @Column(name = "full_name", nullable = false)
    private String name;


    /*
    ==========================================================================
    FIELD: email

    PURPOSE:
    --------
    Stores the user's email address.

    VALIDATION:
    -----------
    1. Cannot be empty.
    2. Must have a valid email format.
    3. Email must be unique.

    ==========================================================================
    */

    @NotBlank(message = "Email is required")
    @Email(message = "Enter a valid email address")
    @Column(unique = true, nullable = false)
    private String email;


    /*
    ==========================================================================
    FIELD: password

    PURPOSE:
    --------
    Stores the user's password.

    VALIDATION:
    -----------
    Password must contain at least 6 characters.

    NOTE:
    -----
    We are currently keeping the password simple while learning
    the authentication flow.

    Later we will add password hashing/security.
    ==========================================================================
    */

    @NotBlank(message = "Password is required")
    @Size(min = 6, message = "Password must contain at least 6 characters")
    private String password;


    /*
    ==========================================================================
    FIELD: role

    PURPOSE:
    --------
    Defines whether the user is an ADMIN or CUSTOMER.

    POSSIBLE VALUES:
    ----------------
    ADMIN
    CUSTOMER

    EnumType.STRING stores the role as text in MySQL.

    ==========================================================================
    */

    @NotNull(message = "Role is required")
    @Enumerated(EnumType.STRING)
    private Role role;


    /*
    ==========================================================================
    FIELD: createdAt

    PURPOSE:
    --------
    Stores the date and time when the user account was created.

    This value is set inside UserService during registration.
    ==========================================================================
    */

    private LocalDateTime createdAt;


    /*
    ==========================================================================
    DEFAULT CONSTRUCTOR
    ==========================================================================
    */

    public User() {
    }


    /*
    ==========================================================================
    PARAMETERIZED CONSTRUCTOR
    ==========================================================================
    */

    public User(Long id,
                String name,
                String email,
                String password,
                Role role,
                LocalDateTime createdAt) {

        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.role = role;
        this.createdAt = createdAt;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR ID
    ==========================================================================
    */

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR NAME
    ==========================================================================
    */

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR EMAIL
    ==========================================================================
    */

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR PASSWORD
    ==========================================================================
    */

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR ROLE
    ==========================================================================
    */

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }


    /*
    ==========================================================================
    GETTER AND SETTER FOR CREATED AT
    ==========================================================================
    */

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}