package com.parking.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/*
==============================================================================
FILE: Vehicle.java

PURPOSE:
--------
This class represents the Vehicle table in the database.

Each object of this class represents one row in the Vehicle table.

Validation rules are added to ensure that invalid data
is not saved into the database.

==============================================================================
*/

@Entity
public class Vehicle {

    /*
    ==============================================================================
    FIELD: id

    PURPOSE:
    --------
    Unique ID for every vehicle.

    It is automatically generated by the database.

    ==============================================================================
    */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /*
    ==============================================================================
    FIELD: ownerName

    PURPOSE:
    --------
    Stores the name of the vehicle owner.

    VALIDATION:
    -----------
    Cannot be empty.
    Minimum 3 characters.
    Maximum 50 characters.

    ==============================================================================
    */

    @NotBlank(message = "Owner name cannot be empty")
    @Size(min = 3, max = 50, message = "Owner name must be between 3 and 50 characters")
    private String ownerName;

    /*
    ==============================================================================
    FIELD: vehicleNumber

    PURPOSE:
    --------
    Stores the vehicle registration number.

    VALIDATION:
    -----------
    Cannot be empty.

    ==============================================================================
    */

    @NotBlank(message = "Vehicle number cannot be empty")
    private String vehicleNumber;

    /*
    ==============================================================================
    FIELD: vehicleType

    PURPOSE:
    --------
    Stores the type of vehicle.

    Example:
    --------
    Car
    Bike
    Truck

    VALIDATION:
    -----------
    Cannot be empty.

    ==============================================================================
    */

    @NotBlank(message = "Vehicle type cannot be empty")
    private String vehicleType;

    /*
    ==============================================================================
    FIELD: status

    PURPOSE:
    --------
    Stores the parking status.

    Example:
    --------
    Parked
    Exited

    VALIDATION:
    -----------
    Cannot be empty.

    ==============================================================================
    */

    @NotBlank(message = "Status cannot be empty")
    private String status;

    /*
    ==============================================================================
    FIELD: entryTime

    PURPOSE:
    --------
    Stores the vehicle entry time.

    ==============================================================================
    */

    private String entryTime;

    /*
    ==============================================================================
    FIELD: exitTime

    PURPOSE:
    --------
    Stores the vehicle exit time.

    ==============================================================================
    */

    private String exitTime;

    // Default Constructor
    public Vehicle() {
    }

    // Parameterized Constructor
    public Vehicle(Long id, String ownerName, String vehicleNumber,
                   String vehicleType, String status,
                   String entryTime, String exitTime) {

        this.id = id;
        this.ownerName = ownerName;
        this.vehicleNumber = vehicleNumber;
        this.vehicleType = vehicleType;
        this.status = status;
        this.entryTime = entryTime;
        this.exitTime = exitTime;
    }

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOwnerName() {
        return ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    public String getVehicleNumber() {
        return vehicleNumber;
    }

    public void setVehicleNumber(String vehicleNumber) {
        this.vehicleNumber = vehicleNumber;
    }

    public String getVehicleType() {
        return vehicleType;
    }

    public void setVehicleType(String vehicleType) {
        this.vehicleType = vehicleType;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getEntryTime() {
        return entryTime;
    }

    public void setEntryTime(String entryTime) {
        this.entryTime = entryTime;
    }

    public String getExitTime() {
        return exitTime;
    }

    public void setExitTime(String exitTime) {
        this.exitTime = exitTime;
    }
}